
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READLINE = 23;
  public static final int DOUBLE = 4;
  public static final int NOTEQUAL = 33;
  public static final int GREATER = 36;
  public static final int PRIVATE = 28;
  public static final int CONTINUE = 31;
  public static final int INTERFACE = 8;
  public static final int INT = 3;
  public static final int MINUS = 44;
  public static final int LESS = 35;
  public static final int FOR = 13;
  public static final int STRINGCONST = 61;
  public static final int NOT = 39;
  public static final int AND = 38;
  public static final int READINTEGER = 22;
  public static final int HEXCONST = 59;
  public static final int LESSEQUAL = 34;
  public static final int INTCONST = 58;
  public static final int RBRACES = 54;
  public static final int LBRACES = 53;
  public static final int OR = 40;
  public static final int COMMA = 48;
  public static final int BOOL = 5;
  public static final int DOUBLECONST = 60;
  public static final int CLASS = 7;
  public static final int DIV = 41;
  public static final int NEWARRAY = 20;
  public static final int ASSIGN = 46;
  public static final int IF = 15;
  public static final int THIS = 10;
  public static final int ID = 57;
  public static final int DOT = 52;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int EQUAL = 32;
  public static final int TRUE = 62;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int LCURLY = 55;
  public static final int ADD = 43;
  public static final int NULL = 9;
  public static final int MOD = 45;
  public static final int BREAK = 18;
  public static final int VOID = 2;
  public static final int DTOI = 24;
  public static final int RCURLY = 56;
  public static final int LBRACK = 49;
  public static final int GREATEREQUAL = 37;
  public static final int COLON = 47;
  public static final int ELSE = 16;
  public static final int PROTECTED = 29;
  public static final int RBRACK = 50;
  public static final int ITOD = 25;
  public static final int ITOB = 27;
  public static final int WHILE = 14;
  public static final int PUBLIC = 30;
  public static final int EXTENDS = 11;
  public static final int BTOI = 26;
  public static final int PROD = 42;
  public static final int STRING = 6;
  public static final int FALSE = 63;
  public static final int LRBRACK = 51;
  public static final int IMPLEMENTS = 12;
  public static final int PRINT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CLASS",
  "INTERFACE",
  "NULL",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "PRIVATE",
  "PROTECTED",
  "PUBLIC",
  "CONTINUE",
  "EQUAL",
  "NOTEQUAL",
  "LESSEQUAL",
  "LESS",
  "GREATER",
  "GREATEREQUAL",
  "AND",
  "NOT",
  "OR",
  "DIV",
  "PROD",
  "ADD",
  "MINUS",
  "MOD",
  "ASSIGN",
  "COLON",
  "COMMA",
  "LBRACK",
  "RBRACK",
  "LRBRACK",
  "DOT",
  "LBRACES",
  "RBRACES",
  "LCURLY",
  "RCURLY",
  "ID",
  "INTCONST",
  "HEXCONST",
  "DOUBLECONST",
  "STRINGCONST",
  "TRUE",
  "FALSE"
  };
}

